#!/bin/bash
# Alternative method to configure reCAPTCHA via Google Cloud Console
# This bypasses the Firebase Console UI error

echo "🔍 Checking Firebase project status..."
echo "Project: stockpilotv1"
echo ""

echo "📋 Manual Steps to Configure reCAPTCHA (Alternative Method):"
echo ""
echo "Since Firebase Console is failing, configure directly in Google Cloud Console:"
echo ""
echo "1. Open Google Cloud Console:"
echo "   https://console.cloud.google.com/security/recaptcha?project=stockpilotv1"
echo ""
echo "2. Find your 'FLYP OTP' key"
echo ""
echo "3. Click on the key to open details"
echo ""
echo "4. Go to 'SMS defense' tab (or 'Settings')"
echo ""
echo "5. Configure:"
echo "   - Enforcement mode: Set to 'AUDIT' or 'ENFORCE'"
echo "   - SMS fraud threshold: Already set to 0.5 ✅"
echo ""
echo "6. Save the configuration"
echo ""
echo "7. Wait 2-3 minutes for changes to propagate"
echo ""
echo "8. Test OTP flow in your app"
echo ""
echo "⚠️  If this also fails, the issue might be:"
echo "   - Billing not enabled (reCAPTCHA Enterprise requires billing)"
echo "   - API not enabled"
echo "   - Project permissions issue"
echo ""
echo "🔗 Direct links:"
echo "   - reCAPTCHA keys: https://console.cloud.google.com/security/recaptcha?project=stockpilotv1"
echo "   - Firebase Auth: https://console.firebase.google.com/project/stockpilotv1/authentication/providers"
echo ""

