#!/bin/bash
echo "🔗 Link reCAPTCHA Key to Firebase Authentication"
echo ""
echo "Your reCAPTCHA Site Key:"
echo "   6LfDEP4rAAAAADI1HEs9K5kEivA90sdZUDj3md5B"
echo ""
echo "📝 Steps to Link:"
echo ""
echo "1. Open this link:"
echo "   https://console.firebase.google.com/project/stockpilotv1/authentication/settings/recaptcha"
echo ""
echo "2. Click 'Configure site keys' button"
echo ""
echo "3. Platform: Web"
echo ""
echo "4. Site Key: 6LfDEP4rAAAAADI1HEs9K5kEivA90sdZUDj3md5B"
echo ""
echo "5. Name: FLYP OTP"
echo ""
echo "6. Click Save"
echo ""
echo "7. Then set enforcement mode to 'AUDIT'"
echo ""
echo "✅ That's it!"
