#!/bin/bash
echo "🔗 Direct Firebase Console Links:"
echo ""
echo "1. Direct reCAPTCHA Settings:"
echo "   https://console.firebase.google.com/project/stockpilotv1/authentication/settings/recaptcha"
echo ""
echo "2. Authentication Settings (main):"
echo "   https://console.firebase.google.com/project/stockpilotv1/authentication/settings"
echo ""
echo "3. Google Cloud Console - reCAPTCHA:"
echo "   https://console.cloud.google.com/security/recaptcha?project=stockpilotv1"
echo ""
echo "4. Identity Toolkit API (check if enabled):"
echo "   https://console.cloud.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=stockpilotv1"
echo ""
echo "5. reCAPTCHA Enterprise API (check if enabled):"
echo "   https://console.cloud.google.com/apis/api/recaptchaenterprise.googleapis.com/overview?project=stockpilotv1"
echo ""
echo "📝 Copy any of these links into your browser!"
