#!/bin/bash
echo "🔍 Firebase Settings Verification Checklist"
echo ""
echo "1️⃣  Phone Authentication (MUST be enabled):"
echo "   https://console.firebase.google.com/project/stockpilotv1/authentication/providers"
echo ""
echo "2️⃣  Authorized Domains (Must include localhost):"
echo "   https://console.firebase.google.com/project/stockpilotv1/authentication/settings?tab=domains"
echo ""
echo "3️⃣  reCAPTCHA Settings (CRITICAL - set enforcement mode):"
echo "   https://console.firebase.google.com/project/stockpilotv1/authentication/settings/recaptcha"
echo ""
echo "4️⃣  Identity Toolkit API (Must be enabled):"
echo "   https://console.cloud.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=stockpilotv1"
echo ""
echo "5️⃣  reCAPTCHA Enterprise API (Must be enabled):"
echo "   https://console.cloud.google.com/apis/api/recaptchaenterprise.googleapis.com/overview?project=stockpilotv1"
echo ""
echo "📝 Open each link and verify the settings!"
