import React, { useState } from 'react';
import { httpsCallable } from 'firebase/functions';
import { auth, functions } from '../../firebase/firebaseConfig';
import { toast } from 'react-toastify';

const AddEmployeeForm = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    role: 'Staff'
  });
  const [loading, setLoading] = useState(false);

  const onChange = (e) => setFormData(prev => ({ ...prev, [e.target.name]: e.target.value }));

  const validate = () => {
    const { name, phone } = formData;
    if (!name?.trim()) return 'Name is required';
    if (!phone?.trim()) return 'Phone is required';
    const normalizedPhone = phone.replace(/\D/g, '');
    if (normalizedPhone.length !== 10) return 'Phone number must have exactly 10 digits';
    return null;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const err = validate();
    if (err) { toast.error(err); return; }

    try {
      setLoading(true);
      const currentUser = auth.currentUser;
      if (!currentUser) {
        toast.error('User not authenticated. Please log in again.');
        return;
      }

      const { name, email, phone, role } = formData;
      const normalizedPhone = phone.replace(/\D/g, '').slice(-10); // keep last 10 digits
      const formattedPhone = `+91${normalizedPhone}`;
      const createEmployee = httpsCallable(functions, 'createEmployee');

      // PIN will be auto-generated by the backend (like distributor)
      const res = await createEmployee({ name, email, phone: formattedPhone, role });
      const data = res?.data;

      if (!data?.success) throw new Error(data?.message || 'Failed to create employee');

      toast.success(`Employee created: ${data.flypEmployeeId} | PIN: ${data.pin} (Valid for 30 days)`);
      setFormData({ name: '', email: '', phone: '', role: 'Staff' });
    } catch (e2) {
      console.error('Create employee error:', e2);
      toast.error(e2?.message || 'Failed to create employee');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4 max-w-md">
      <div>
        <label className="block text-sm text-gray-300 mb-1">Name</label>
        <input
          name="name"
          value={formData.name}
          onChange={onChange}
          className="w-full bg-white/10 border border-white/20 px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-white placeholder-gray-400"
          placeholder="Employee name"
        />
      </div>

      <div>
        <label className="block text-sm text-gray-300 mb-1">Email (optional)</label>
        <input
          type="email"
          name="email"
          value={formData.email}
          onChange={onChange}
          className="w-full bg-white/10 border border-white/20 px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-white placeholder-gray-400"
          placeholder="name@example.com"
        />
      </div>

      <div>
        <label className="block text-sm text-gray-300 mb-1">Phone Number</label>
        <input
          name="phone"
          value={formData.phone}
          onChange={onChange}
          className="w-full bg-white/10 border border-white/20 px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-white placeholder-gray-400"
          placeholder="+91XXXXXXXXXX"
        />
      </div>

      <div>
        <label className="block text-sm text-gray-300 mb-1">Role</label>
        <select
          name="role"
          value={formData.role}
          onChange={onChange}
          className="w-full bg-white/10 border border-white/20 px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-white"
        >
          <option>Staff</option>
          <option>Billing</option>
          <option>Inventory</option>
          <option>Analytics</option>
          <option>Manager</option>
        </select>
      </div>


      <button
        type="submit"
        disabled={loading}
        className={`w-full bg-gradient-to-r from-blue-600 to-teal-500 text-white py-2 rounded-md ${loading ? 'opacity-70 cursor-not-allowed' : ''}`}
      >
        {loading ? 'Creating…' : 'Create Employee'}
      </button>

      <p className="text-xs text-gray-400 mt-2">
        Employee ID and PIN will be auto-generated and shown in the success message. PIN is valid for 30 days.
      </p>
    </form>
  );
};

export default AddEmployeeForm;